### ISSUE TITLE
loaded, fetched and ready are always false before and after load Collection

### ISSUE THREAD

**Issue by FranciscoSanvicente** [jircdev/reactive-model#12]
## Loaded, fetched and ready are always false before and after load Collection

When loading a Collection the properties loaded, fetched and ready are false before and after the items are loaded and also fetching remains true once the items are loaded.

**Comment by jircdev** [comment]
Hi @FranciscoSanvicente ,

I see you've encountered an issue. To assist you effectively,  w'll need more details about the problem you're facing.

- Plaase, share the relevant code snippets or configuration settings related to the issue, this will help us to identtify the problem faster.
- Please tell me if this problem is only in collections or in Items too.

If there's any additional context or information that might be relevant to the issue, please provide it here.

Thank you.

**Comment by FranciscoSanvicente** [comment]
Hi @jircdev 

To solve the problem you have to make an instance of a Collection object, subscribe to the change events and place the corresponding console to see the changes on the instance and do the load, example the following code reproduced by console, here you can see how loaded, fetched and ready are false before and after the load

``const { Companies } = await beyond.import('jview/entities.ts');
const companies = new Companies();
const bind = () => {  console.log(companies.ready); console.log(companies.fetched); console.log(companies.loaded); console.log(companies.fetching); console.log(companies.items)
}
companies.on("change", bind)
const response = await companies.load();``


![alt text](https://cdn.discordapp.com/attachments/884890492427464774/1151988313092280391/Captura_de_pantalla_2023-09-14_125132.png "Title")

The problem also happens with the Item object, to reproduce it follow the same steps, in this case you can see loaded and fetched are always false, ready is true before the company name is valid so it goes to true before loading, fetching was undefined until and then it goes to false.

![alt text](https://cdn.discordapp.com/attachments/884890492427464774/1151988400962936903/image.png "Title")

``const { Company } = await beyond.import('jview/entities.ts');
const company = new Company();
const bind = () => {  console.log(1, company.ready, company.fetched, company.loaded, company.fetching, company.name); 
}
company.on("change", bind)
const response = await company.load({id: 1})``
