### ISSUE TITLE
Item Reset

### ISSUE THREAD

**Issue by FranciscoSanvicente** [jircdev/reactive-model#13]
### Item Reset

It is proposed that the Item object has a method that allows to reset the Item, this is because in a use case after making a publish we needed to reset the Item information to recreate another Item and make a publish but keeping the same instance, so it is requested to reset the Item to be able to have the same object to create Items.

**Comment by jircdev** [comment]
Hi @FranciscoSanvicente,

I understand your request for a method to reset the Item object, but it's essential to consider the design principles here. Typically, each Item is associated with a specific record, and it's considered a best practice to treat them as singletons. Creating a new instance of the Item when you need to work with a different record is the recommended approach.

Could you provide more details about your use case? Perhaps there's an alternative solution we can explore to ensure you're working within the best practices of our system.

Feel free to share more about your specific requirements, and we can discuss the most effective approach.

**Comment by FranciscoSanvicente** [comment]
The issue is closed as it was considered best practice to create a new instance when working with a new Item.
