### ISSUE TITLE
🔴🔴🔴 `instanceId` Property Conflict

### ISSUE THREAD

**Issue by eynort** [jircdev/reactive-model#18]
Hello ReactiveModel team 🤝

I am encountering an issue while using the ReactiveModel library in my application. I am working with a custom entity that requires a property named instanceId. However, I've noticed that the item entity also uses an internal property with the same name, instanceId, in its operations. When my custom entity interacts with Item entity, there is a conflict due to the name overlap in the instanceId property. This results in Item either overwriting or disregarding my entity’s instanceId property, leading to errors and undesired behaviors in the application.

Thank you in advance 🚀.
Bryant Caballero

**Comment by jircdev** [comment]
@veD-tnayrB can you share the message or print screen of the error?

**Comment by eynort** [comment]
> @veD-tnayrB can you share the message or print screen of the error?

There is no error message, simply the value of the instanceId set in the provider does not arrive, the value defined by the reactive is received.

**Comment by eynort** [comment]
Solved in v1.1.11.
https://www.npmjs.com/package/@beyond-js/reactive
