### ISSUE TITLE
Fix: remove console.log

### ISSUE THREAD

**Issue by FranciscoSanvicente** [jircdev/reactive-model#27]
# Fix: remove console.log

there is a console.log in the collections
<img width="605" alt="image" src="https://github.com/jircdev/reactive-model/assets/64644109/93b8ca34-7f9f-4f03-899f-bd99b00f7b8a">

<img width="419" alt="image" src="https://github.com/jircdev/reactive-model/assets/64644109/1c89d4a0-7c41-4f8a-805b-4c4383635dc8">

### removal is requested

**Comment by eynort** [comment]
Solved in v1.1.11 🤗
https://www.npmjs.com/package/@beyond-js/reactive
