### ISSUE TITLE
Cannot set a version other than version 1 in indexedDB 🔴

### ISSUE THREAD

**Issue by eynort** [jircdev/reactive-model#3]
# Description

At the time of establishing the configuration of the db of indexedDB making use of `DBManager.config` and establishing a different version to the 1, for example 0.0.1 is not going to recognize the db, verifying the reason I found that in: `modules\database\index.ts`:23 the version 1 is harcodea, which causes that when wanting to look for the database configured and this to have a different version for but of having configured it well it does not obtain it.

![image](https://github.com/jircdev/reactive-model/assets/90587911/7f32a905-7769-4c4e-a34c-453e9a4f8beb)

**Comment by jircdev** [comment]
The depicted database in your image is an internal reactive database and does not reflect the store created per app. Therefore, you observed the version directly. Additionally, the "0.0.1" structure is incorrect for indexedDB versioning. The version parameter of DBManager.config is the same "version" parameter used when working directly with IndexedDB, necessitating the use of an integer.
